"""add_mission_type

Revision ID: 995377a9f175
Revises: b8d4e2f3a561
Create Date: 2026-06-20 18:56:02.503054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '995377a9f175'
down_revision: Union[str, Sequence[str], None] = 'b8d4e2f3a561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loadouts', sa.Column('context', sa.String(length=120), nullable=True))
    op.add_column('missions', sa.Column('mission_type', sa.String(), server_default='regular', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('missions', 'mission_type')
    op.drop_column('loadouts', 'context')
    # ### end Alembic commands ###
