"""add captures and capture_candidates tables

Revision ID: dcab916f9edd
Revises: 6ef1e56db9e1
Create Date: 2026-06-17 20:01:32.543739

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dcab916f9edd"
down_revision: str | Sequence[str] | None = "6ef1e56db9e1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "captures",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "public_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("input_type", sa.String(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_index(
        "idx_captures_created", "captures", [sa.literal_column("created_at DESC")], unique=False
    )
    op.create_index("idx_captures_user_status", "captures", ["user_id", "status"], unique=False)
    op.create_table(
        "capture_candidates",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "public_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("capture_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("platform_hint", sa.String(), nullable=True),
        sa.Column("igdb_id", sa.BigInteger(), nullable=True),
        sa.Column("igdb_title", sa.String(), nullable=True),
        sa.Column("igdb_cover_url", sa.String(), nullable=True),
        sa.Column("igdb_summary", sa.Text(), nullable=True),
        sa.Column("igdb_genres", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("igdb_first_release_date", sa.Date(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("matched_game_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["capture_id"], ["captures.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["matched_game_id"],
            ["games.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("capture_candidates")
    op.drop_index("idx_captures_user_status", table_name="captures")
    op.drop_index("idx_captures_created", table_name="captures")
    op.drop_table("captures")
    # ### end Alembic commands ###
